### ISSUE TITLE
网站连接打不开了

### ISSUE THREAD

**Issue by Raindrips** [tomoya92/dstmod-tutorial#10]
指向“https://cdnjs.cloudflare.com/ajax/libs/docsify/4.12.2/docsify.min.js”的 <script> 加载失败。 dstmod-tutorial:42:1 指向“https://cdnjs.cloudflare.com/ajax/libs/docsify/4.12.2/plugins/search.min.js”的 <script> 加载失败。 dstmod-tutorial:43:1 指向“https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/components/prism-bash.min.js”的 <script> 加载失败。 dstmod-tutorial:44:1 指向“https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/components/prism-lua.min.js”的 <script> 加载失败。

**Comment by atjiu** [comment]
可能cdn暂时抽风，等等再试试
