### ISSUE TITLE
关于mod文件夹位置的疑问

### ISSUE THREAD

**Issue by IcyFeather233** [tomoya92/dstmod-tutorial#13]
您好，我发现我的电脑中，在 `D:\Steam\steamapps\common\Don't Starve Together\mods` 和 `C:\SteamLibrary\steamapps\common\Don't Starve Together\mods` 这两个位置都有很多名为 `workshop-xxx` 的 mod 文件夹，但是我在两个目录下面创建 `quick-start` 文件夹并创建了 `modinfo.lua` 和 `modmain.lua` 后，饥荒创建游戏，选择mod，本地mod中仍然找不到 quick-start 这个 mod，想问一下是我的文件目录选错了吗

**Comment by atjiu** [comment]
在steam里对游戏点右键，选择浏览本地文件夹，就知道你游戏装在哪地方了

**Comment by IcyFeather233** [comment]
照着 “入门”-“创建第一个mod”做没有出现quick-start的mod

我的步骤：

首先点击这里进入游戏文件夹
![image](https://github.com/atjiu/dstmod-tutorial/assets/56245435/416fca48-ebda-4c5e-8fbd-ca41ecd9c536)

进入了 `C:\SteamLibrary\steamapps\common\Don't Starve Together` 这个目录下面
然后点击mods文件夹
![image](https://github.com/atjiu/dstmod-tutorial/assets/56245435/80ea3644-28e9-45fd-8813-4fe1db5c1fd7)

随后按照教程创建了两个文件，内容和教程给的完全一致：
![image](https://github.com/atjiu/dstmod-tutorial/assets/56245435/73942987-3e31-4f42-a89d-421dfef7a8bc)

然后搜不到这个mod
![image](https://github.com/atjiu/dstmod-tutorial/assets/56245435/7e01dced-b1fe-4b1b-96b2-109983cb8c6f)

**Comment by IcyFeather233** [comment]
没事了 把饥荒所有东西删了重装之后就好了

**Comment by atjiu** [comment]
在服务器模组里看看有没有

发自我的iPhone
