### ISSUE TITLE
请问 PLACER_SCALE 的大小如何确定

### ISSUE THREAD

**Issue by peiyanlu** [tomoya92/dstmod-tutorial#15]
请问建筑显示范围的贴图缩放大小是如何计算的，他和地皮大小有什么关联？

例如佣人mod 5 格地皮的缩放大小为 1.78，官方雪球发射器 2.3 格地皮的缩放大小为 1.55，没发现有什么关联

**Comment by atjiu** [comment]
不是太清楚这个，我一般都是进游戏看效果进行微调的
