### ISSUE TITLE
关于widget的疑问

### ISSUE THREAD

**Issue by clcaod** [tomoya92/dstmod-tutorial#16]
我们添加一个widget的步骤大致如下:

1. 定义一个widget继承widget,诸如此
```lua
Class(Widget,function(self,owner) end)
````

2.在modmain.lua中引入widget
```lua
AddClassPostConstruct("widgets/controls",function(self)
    self.DemoBadge = self:AddChild(DemoBadge(self.owner))
end)
```

那么最重要的也就是第三步，如何给这些widget动态传递数据问题，widget给出的demo很简单，通过构建虚entity的方式执行周期任务，不断的调用self.DemoBadge，这是一种方法，但是这个数据源他仅限于AddClassPostConstruct这个代码块中。

但实际情况是，我想要在使用modmain.lua中其他地方的逻辑来控制这个widget诸如show和hide,但我发现没办法在`AddClassPostConstruct `这个代码块中获取modmain.lua中的全局变量。
如：
```lua
local variable = "hello"
AddClassPostConstruct("widgets/controls",function(self)
    self.DemoBadge = self:AddChild(DemoBadge(self.owner))
    self.owner:DoPeriodicTask(1,function()
        self.DemoBadge:OnUpdate(variable)
    end)

end)
```

其他地方对变量**variable的改变**并不会改变这个数据的显示。

根据看其他Modder的代码时发现，有一种做法是通过owner:ListenerForEvent()，通过事件推送数据，然后widget监听到事件拿到数据，但我发现一个问题就是，这个owner他是玩家对象，但是和我在其他地方(TheWord:ListenForEvent("ms_playerjoined", OnPlayerJoin))这个玩家对象并不一致，所以说一个玩家加入世界不仅仅存在一个实体对象对吗，这从理解上很困惑，因为一个玩家加入世界应该只有一个entity才对。

目前我能想到的widget获取数据的方式就这两种:
1. AddClassPostConstruct代码块中定义的变量
2. 事件监听方式(有疑问)

**Comment by atjiu** [comment]
如果你仔细查看过UI部分的源码就会发现，在屏幕上显示的所有的Widget最终都会被添加到playerhud里，在playerhud里的 `function PlayerHud:SetMainCharacter(maincharacter)` 这个方法中，可以看到将playerhud自身绑定到了玩家对象的HUD上

```lua
function PlayerHud:SetMainCharacter(maincharacter)
    if maincharacter then
        maincharacter.HUD = self
```

这样的话，操作Widget就可以通过 `ThePlayer.HUD.xxx` 来进行操作

举个例子：

比如右下角的地图控制UI是在 controls.lua 里被添加的，然而 Controls 在playerhud 里被绑到了 `controls` 上

```lua
function PlayerHud:SetMainCharacter(maincharacter)
    if maincharacter then
        maincharacter.HUD = self
        self.owner = maincharacter

		self._CraftingHintAllRecipesEnabled = Profile:GetCraftingHintAllRecipesEnabled() -- cache the value so we can refresh the crafting menu with it changes

        self:CreateOverlays(self.owner)
        self.controls = self.root:AddChild(Controls(self.owner))
```

---

关于你提到的添加动态数据的问题，我一般的做法是通过 `复制组件` 来实现的，也就是从带有 `_replica` 的组件里取数据

- 如果你的数据源是跟玩家自己绑定的，就可以定义一个组件`abc`，将组件添加到玩家身上，然后通过 `abc_replica` 同步到客机，在widget里就能通过 `owner.replica.abc.data` 拿到数据了 
- 如果你的数据源是全局所有玩家共用的，就要找一个游戏内全局共用的东西来存放这个数据，我一般选用的是 `forest`, `cave` 这两个世界对象上，取数据就可以用 `TheWorld.components.abc.data` 来获取
