### ISSUE TITLE
关于网页图文教程一个小细节问题

### ISSUE THREAD

**Issue by Windfine-Guto** [tomoya92/dstmod-tutorial#17]
您好，您写的这篇网页图文教程，句子有点奇怪，具体的路径名被高亮标识出来放在句子的后面，我读了半天才搞明白
![QQ图片20231108112830](https://github.com/atjiu/dstmod-tutorial/assets/64732534/20a43c0e-34f1-4ff7-a4c6-0d2c7447f6ec)

**Comment by atjiu** [comment]
我看着是正常的
![image](https://github.com/atjiu/dstmod-tutorial/assets/6915570/b3328c40-696e-4ec5-b4e3-bae95e13d058)

**Comment by Dr-WeiAL** [comment]
开了网页翻译是这样的

**Comment by Windfine-Guto** [comment]
关闭网页翻译后刷新没问题了
