### ISSUE TITLE
大佬好，想问问如何添加新的三维.....

### ISSUE THREAD

**Issue by WolfEllobo** [tomoya92/dstmod-tutorial#18]
我去看了好多大佬的mod，和mod制作群里的示例，结果都不太理想，每次都是会卡在选完人之后进游戏的界面....
![{31AB46B6-0BBF-4f97-81B0-D484EDEED2EC}](https://github.com/atjiu/dstmod-tutorial/assets/63346269/f9eb831e-a18f-4998-8eb5-91092d32469a)

**Comment by atjiu** [comment]
可以抄官方的三围代码，或者找有新状态的mod的代码抄

进游戏卡住应该是报错了，查一下日志，看看是哪报错，修一下就好了
