### ISSUE TITLE
鼠标监听相关

### ISSUE THREAD

**Issue by dydhyhwu** [tomoya92/dstmod-tutorial#7]
我现在如果想达成下面两个目的的话，需要哪些api或者hook：
1. 类似全能面板，查看鼠标指向的物品信息（查看这个该怎么做）
2. 类似show me，监听鼠标拿起， 放下的事件（看了箱子检测的代码，里面的hook能达到这个效果，想了解下还有其它的么）

这个仓库真的太赞了！

**Comment by atjiu** [comment]
去看  全能面板，showme的源码是怎么写的，我没看过相关的代码，不好回答
